name: Release

on:
  push:
    tags:
      - '**'

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
      CF_API_KEY: ${{ secrets.CF_API_KEY }}
    steps:
      - name: Clone project
        uses: actions/checkout@v1
      - name: Package and release
        uses: BigWigsMods/packager@master
      - name: Package and release for Classic
        uses: BigWigsMods/packager@master
        with:
          args: -g classic
